project_id = "hardstop"

[api]
enabled = true
port = 54321

[edge_runtime]
enabled = true
policy = "per_worker"
inspector_port = 8083

[functions.process-answer]
verify_jwt = false

[functions.evaluate-answer]
verify_jwt = false
